before_script:
  #- yum install which -y
  # install ssh-agent if not already installed, it is required by docker
  - "which ssh-agent || ( yum install openssh-clients -y )"
  # run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)
  # add the ssh key stored in SSH_PRIVATE_KEY variable to the agent store
  #- ssh-add <(echo "$SSH_PRIVATE_KEY")
  # for docker builds disable host key checking although this can lead to
  # mitm attacks; only use this in docker or it will overwrite the host
  # ssh config!
  #- mkdir -p ~/.ssh
  #- '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - whoami
  - pwd
after_script:
  - whoami
  - pwd
stages:
  - master
  - prod
develop:
  stage: master
  only:
    # This build will run only when something is pushed to the develop branch.
    - master
  script:
    - pwd && su dev && whoami
    - cd /home/dev/htdocs/armcobarriers/
    - git pull
    - bootstrap="$(git log -1 --pretty=%B | grep bootstrap)" && ([[ $bootstrap ]] && bash bin/bootstrap.sh -e d)
    - sass="$(git log -1 --pretty=%B | grep sass)" && ([[ $sass ]] && sass platform/themes/armcobarriers/assets/sass/common.scss:public/themes/armcobarriers/css/common.css --style compressed)
    - npm="$(git log -1 --pretty=%B | grep npm)" && ([[ $npm ]] && npm install n -g && n stable && n latest && npm install && npm update && npm run dev)
    - migrate="$(git log -1 --pretty=%B | grep migrate)" && ([[ $migrate ]] && yes | php artisan migrate)
    - delivery="$(git log -1 --pretty=%B | grep delivery)" && ([[ $delivery ]] && bash bin/delivery.sh -e p)
    - php artisan config:clear
    - php artisan cache:clear
    - npm update && npm run dev
    - php artisan view:clear
    - chown -R dev:dev /home/dev/htdocs/armcobarriers/
    - pwd
